### ISSUE TITLE
Project structure and licenses

### ISSUE THREAD

**Issue by 448-OG** [RustaceansKenya/RustaceansKenyaWebapp#2]
Create a cargo workspace project structure for this repo with the following requirements:

1. Create a cargo workspace that file with metadata `workspace = { members = [] }
`.
2. Add workspace resolver to be "2" with the format `workspace = { members = [], resolver = "2" }`
3. Create a crate called `frontend` for all the frontend code
4. Create a crate called `backend` for all the backend code
5. add both crates to the workspace file if they were not added automatically
6. Add the description for both crates in their manifest file detailing what the crates would do
7. Add authors for the crates as `Rustaceans Kenya` with no email field for the author
8. Add `Apache-2.0 OR MIT` licenses for the license field in the manifest files for both crates
9. Withing the workspace folder add a `deny.toml` file which allows `MIT` and `Apache-2.0` licenses to be enabled by default. The `deny.toml` file is automatically created using [https://crates.io/crates/cargo-deny](https://crates.io/crates/cargo-deny)

**Comment by jim4067** [comment]
let me take this and have it wrapped before the week ends.

**Comment by jim4067** [comment]
let me take this and have it done by the end of the week.

**Comment by 448-OG** [comment]
That's fine, it should take long though. You can also do 1 to 5 since it's easier then do more PRs as you go
